name: Build & Publish ALPS Theme

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: prepare
        name: Install Dependencies
        run: |
          npm install

      - id: build-components
        name: Build Components
        run: |
          npm run build

      - id: build-theme
        name: Build Theme
        run: |
          npm run wp:build:theme

      - id: publish
        name: Publish Theme
        run: |
          npm run wp:release:theme
